name: Generate Crime Data RSS Feed

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on a schedule (this example is every hour)
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    # Add this permissions block to allow the action to write to the repository
    permissions:
      contents: write

    steps:
      # 1. Checks out your repository's code so the script can run
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the Node.js environment required to run the script
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installs the necessary libraries ('node-fetch' and 'rss')
      - name: Install dependencies
        run: npm install node-fetch rss

      # 4. Runs your script to generate the feed-{fsa}.xml files (multiple)
      - name: Generate RSS feeds
        run: node ./scripts/generate-rss.js  # Ensure this matches your filename
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}  # Add your API key to repo secrets

      # 5. Commits the updated feed-{fsa}.xml files back to the repository if they have changed
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Auto-update crime data RSS feeds'
          file_pattern: 'feed-*.xml'  # Commit all FSA-specific feeds
