# This is the name of the automated workflow
name: Update Crime Data

# This section defines when the workflow will run
on:
  # 1. Run automatically on a schedule (e.g., every day at 5 AM UTC)
  schedule:
    - cron: '0 11 * * *'
  # 2. Also allow running it manually from the GitHub Actions tab
  workflow_dispatch:

# This section defines the jobs the workflow will perform
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # This is the new section that grants the necessary permissions
    permissions:
      contents: write
    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python so we can run our script
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Run the data processing script
      - name: Run data processing script
        run: python process_data.py

      # Step 4: Commit the newly generated JSON files back to the repository
      - name: Commit and push if data has changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated data update"
            # Pull the latest changes from the remote repository before pushing
            git pull --rebase
            git push
          else
            echo "No data changes to commit."
          fi
